apiVersion: 1
groups:
  - orgId: 1
    name: HPA Alerts
    folder: Aegis
    interval: 10s
    rules:
      - uid: hpa_scaling_change
        title: HPA Scaling Change
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              editorMode: code
              expr: abs(delta(kube_horizontalpodautoscaler_status_current_replicas{namespace="demo"}[5m]))
              legendFormat: '{{horizontalpodautoscaler}}'
              range: true
              intervalMs: 15000
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: "__expr__"
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: last
                  type: query
              type: classic_conditions
        noDataState: OK
        execErrState: Error
        for: 1m
        annotations:
          description: "HPA {{ $labels.horizontalpodautoscaler }} has scaled replicas."
          summary: "HPA scaling change detected"
        labels:
          severity: info
          category: scaling